CAR_BRAND = [
    ('Acura', 'Acura'),
    ('Alfa Romeo', 'Alfa Romeo'),
    ('Aston Martin', 'Aston Martin'),
    ('Audi', 'Audi'),
    ('Bentley', 'Bentley'),
    ('BMW', 'BMW'),
    ('Bugatti', 'Bugatti'),
    ('Cadillac', 'Cadillac'),
    ('Chevrolet', 'Chevrolet'),
    ('Chrysler', 'Chrysler'),
    ('Citroen', 'Citroen'),
    ('Dacia', 'Dacia'),
    ('Daewoo', 'Daewoo'),
    ('Daihatsu', 'Daihatsu'),
    ('Dodge', 'Dodge'),
    ('Ferrari', 'Ferrari'),
    ('Fiat', 'Fiat'),
    ('Ford', 'Ford'),
    ('Genesis', 'Genesis'),
    ('GMC', 'GMC'),
    ('Honda', 'Honda'),
    ('Hummer', 'Hummer'),
    ('Hyundai', 'Hyundai'),
    ('Infiniti', 'Infiniti'),
    ('Isuzu', 'Isuzu'),
    ('Jaguar', 'Jaguar'),
    ('Jeep', 'Jeep'),
    ('Kia', 'Kia'),
    ('Koenigsegg', 'Koenigsegg'),
    ('Lamborghini', 'Lamborghini'),
    ('Land Rover', 'Land Rover'),
    ('Lexus', 'Lexus'),
    ('Lincoln', 'Lincoln'),
    ('Lotus', 'Lotus'),
    ('Maserati', 'Maserati'),
    ('Mazda', 'Mazda'),
    ('McLaren', 'McLaren'),
    ('Mercedes', 'Mercedes'),
    ('Mini', 'Mini'),
    ('Mitsubishi', 'Mitsubishi'),
    ('Nissan', 'Nissan'),
    ('Opel', 'Opel'),
    ('Pagani', 'Pagani'),
    ('Peugeot', 'Peugeot'),
    ('Plymouth', 'Plymouth'),
    ('Porsche', 'Porsche'),
    ('Ram', 'Ram'),
    ('Renault', 'Renault'),
    ('Rolls Royce', 'Rolls Royce'),
    ('Saab', 'Saab'),
    ('Saturn', 'Saturn'),
    ('Scion', 'Scion'),
    ('Seat', 'Seat'),
    ('Skoda', 'Skoda'),
    ('Smart', 'Smart'),
    ('Subaru', 'Subaru'),
    ('Suzuki', 'Suzuki'),
    ('Tesla', 'Tesla'),
    ('Toyota', 'Toyota'),
    ('Volkswagen', 'Volkswagen'),
    ('Volvo', 'Volvo')
]

# Trier la liste par ordre alphabétique
CAR_BRAND.sort(key=lambda x: x[0])

# Supprimer les doublons en utilisant un ensemble (set)
CAR_BRAND = list(set(CAR_BRAND))

# Retrier la liste après avoir supprimé les doublons
CAR_BRAND.sort(key=lambda x: x[0])

COLOR_CHOICES = [
    ('Noir', 'Noir'),
    ('Blanc', 'Blanc'),
    ('Rouge', 'Rouge'),
    ('Bleu', 'Bleu'),
    ('Gris', 'Gris'),
    ('Marron', 'Marron'),
    ('Orange', 'Orange'),
    ('Violet', 'Violet'),
    ('Vert', 'Vert'),
    ('Jaune', 'Jaune'),
    ('Beige', 'Beige'),
    ('Rose', 'Rose'),
]