# Generated by Django 4.2.6 on 2024-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="images/user.png", null=True, upload_to="photos/%Y/"
            ),
        ),
    ]
