# Generated by Django 4.2.6 on 2024-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="images/user.png", null=True, upload_to="images/%Y/"
            ),
        ),
    ]
