# Generated by Django 4.2.11 on 2025-10-25 08:43

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_indexable', models.BooleanField(default=True, help_text='Décoche pour noindex.')),
                ('follow_links', models.BooleanField(default=True, help_text='Décoche pour nofollow.')),
                ('canonical_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='≤ 60–70 caractères.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='≤ 155–160 caractères.', max_length=160)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_indexable', models.BooleanField(default=True, help_text='Décoche pour noindex.')),
                ('follow_links', models.BooleanField(default=True, help_text='Décoche pour nofollow.')),
                ('canonical_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='≤ 60–70 caractères.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='≤ 155–160 caractères.', max_length=160)),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('content', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_cover)),
                ('cover_alt', models.CharField(blank=True, max_length=125)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('published', 'Publié')], db_index=True, default='draft', max_length=10)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False, help_text='Mise en avant (homepage, blocs SEO).')),
                ('is_deleted', models.BooleanField(default=False)),
                ('reading_time_min', models.PositiveSmallIntegerField(default=1, help_text='Temps de lecture estimé.')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to=blog.models.upload_inline_image)),
                ('alt_text', models.CharField(help_text='Texte alternatif (obligatoire).', max_length=125)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'publish_at'], name='blog_post_status_e6cf81_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
    ]
