# Generated by Django 4.2.11 on 2025-10-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='canonical_url',
        ),
    ]
