# Generated by Django 4.2.11 on 2025-10-25 10:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_category_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Contenu de l’article.', null=True, verbose_name='Contenu'),
        ),
    ]
