# Generated by Django 4.2.11 on 2025-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='≤ 155–160 caractères.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='≤ 155–160 caractères.'),
        ),
    ]
