# Generated by Django 4.2.11 on 2025-10-25 11:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_cover),
        ),
        migrations.AddField(
            model_name='category',
            name='cover_alt',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
