# Generated by Django 4.2.6 on 2024-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
