# Generated by Django 4.2.6 on 2024-08-29 13:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
