# Generated by Django 4.2.11 on 2025-10-25 10:58

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
