# Generated by Django 4.2.6 on 2024-05-12 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Acura", "Acura"),
                            ("Alfa Romeo", "Alfa Romeo"),
                            ("Aston Martin", "Aston Martin"),
                            ("Audi", "Audi"),
                            ("BMW", "BMW"),
                            ("Bentley", "Bentley"),
                            ("Bugatti", "Bugatti"),
                            ("Cadillac", "Cadillac"),
                            ("Chevrolet", "Chevrolet"),
                            ("Chrysler", "Chrysler"),
                            ("Citroen", "Citroen"),
                            ("Dacia", "Dacia"),
                            ("Daewoo", "Daewoo"),
                            ("Daihatsu", "Daihatsu"),
                            ("Dodge", "Dodge"),
                            ("Ferrari", "Ferrari"),
                            ("Fiat", "Fiat"),
                            ("Ford", "Ford"),
                            ("GMC", "GMC"),
                            ("Genesis", "Genesis"),
                            ("Honda", "Honda"),
                            ("Hummer", "Hummer"),
                            ("Hyundai", "Hyundai"),
                            ("Infiniti", "Infiniti"),
                            ("Isuzu", "Isuzu"),
                            ("Jaguar", "Jaguar"),
                            ("Jeep", "Jeep"),
                            ("Kia", "Kia"),
                            ("Koenigsegg", "Koenigsegg"),
                            ("Lamborghini", "Lamborghini"),
                            ("Land Rover", "Land Rover"),
                            ("Lexus", "Lexus"),
                            ("Lincoln", "Lincoln"),
                            ("Lotus", "Lotus"),
                            ("Maserati", "Maserati"),
                            ("Mazda", "Mazda"),
                            ("McLaren", "McLaren"),
                            ("Mercedes", "Mercedes"),
                            ("Mini", "Mini"),
                            ("Mitsubishi", "Mitsubishi"),
                            ("Nissan", "Nissan"),
                            ("Opel", "Opel"),
                            ("Pagani", "Pagani"),
                            ("Peugeot", "Peugeot"),
                            ("Plymouth", "Plymouth"),
                            ("Porsche", "Porsche"),
                            ("Ram", "Ram"),
                            ("Renault", "Renault"),
                            ("Rolls Royce", "Rolls Royce"),
                            ("Saab", "Saab"),
                            ("Saturn", "Saturn"),
                            ("Scion", "Scion"),
                            ("Seat", "Seat"),
                            ("Skoda", "Skoda"),
                            ("Smart", "Smart"),
                            ("Subaru", "Subaru"),
                            ("Suzuki", "Suzuki"),
                            ("Tesla", "Tesla"),
                            ("Toyota", "Toyota"),
                            ("Volkswagen", "Volkswagen"),
                            ("Volvo", "Volvo"),
                        ],
                        max_length=100,
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Noir", "Noir"),
                            ("Blanc", "Blanc"),
                            ("Rouge", "Rouge"),
                            ("Bleu", "Bleu"),
                            ("Gris", "Gris"),
                            ("Marron", "Marron"),
                            ("Orange", "Orange"),
                            ("Violet", "Violet"),
                            ("Vert", "Vert"),
                            ("Jaune", "Jaune"),
                            ("Beige", "Beige"),
                            ("Rose", "Rose"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
