# Generated by Django 4.2.11 on 2025-05-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('start_city', models.CharField(max_length=200)),
                ('end_city', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('seat_go', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('premium', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('driver', 'Conducteur'), ('passenger', 'Passager')], default='driver', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='homework.homework')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('homework', 'day')},
            },
        ),
    ]
