# Generated by Django 4.2.11 on 2025-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_homework_friday_active_homework_friday_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='seat_back',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
