# Generated by Django 4.2.11 on 2025-05-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homework_seat_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='seat_back',
            new_name='seat_return',
        ),
    ]
