# Generated by Django 4.2.11 on 2025-05-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_rename_seat_back_homework_seat_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeworkSchedule',
        ),
    ]
