# Generated by Django 4.2.6 on 2024-08-20 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("covoiturages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="covoiturage",
            old_name="tuesday_return_time",
            new_name="tuesday_return",
        ),
    ]
