# Generated by Django 5.2 on 2025-04-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('departure', models.CharField(max_length=255)),
                ('arrival', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aftu.busline')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aftu.stop')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('line', 'stop')},
            },
        ),
        migrations.AddField(
            model_name='busline',
            name='stops',
            field=models.ManyToManyField(through='aftu.BusStop', to='aftu.stop'),
        ),
    ]
