# Generated by Django 5.2 on 2025-04-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aftu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busline',
            name='name',
        ),
    ]
