# Generated by Django 4.2.6 on 2023-11-01 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('user_type', models.CharField(choices=[('Conducteur', 'Conducteur'), ('Passager', 'Passager')], default='Conducteur', max_length=20)),
                ('trip_type', models.CharField(choices=[('Aller Simple', 'Aller Simple'), ('Aller Retour', 'Aller Retour')], default='Aller Simple', max_length=20)),
                ('start_city', models.CharField(choices=[('Almadies', 'Almadies'), ('Aéroport AIBD', 'Aéroport AIBD'), ('Bambilor', 'Bambilor'), ('Bargny', 'Bargny'), ('Ben Baraque', 'Ben Baraque'), ('Ben Tally', 'Ben Tally'), ('Bignona', 'Bignona'), ('Castor', 'Castor'), ('Centre Cutlure de Diamniadio', 'Centre Cutlure de Diamniadio'), ('Colobane', 'Colobane'), ('Dakar', 'Dakar'), ('Derklé', 'Derklé'), ('Diamniadio', 'Diamniadio'), ('Dieuppeul', 'Dieuppeul'), ('Diourbel', 'Diourbel'), ('Fann', 'Fann'), ('Fass', 'Fass'), ('Fatick', 'Fatick'), ('Goudomp', 'Goudomp'), ('Grand Dakar', 'Grand Dakar'), ('Grand Yoff', 'Grand Yoff'), ('Guinguinéo', 'Guinguinéo'), ('Guédiawaye', 'Guédiawaye'), ('HLM', 'HLM'), ('Hann', 'Hann'), ('Kaffrine', 'Kaffrine'), ('Kanel', 'Kanel'), ('Kaolack', 'Kaolack'), ('Keur Massar', 'Keur Massar'), ('Keur Ndiaye Lo', 'Keur Ndiaye Lo'), ('Kolda', 'Kolda'), ('Koumpentoum', 'Koumpentoum'), ('Koungheul', 'Koungheul'), ('Kounoune', 'Kounoune'), ('Kédougou', 'Kédougou'), ('Lac Rose', 'Lac Rose'), ('Liberté 5', 'Liberté 5'), ('Liberté 6', 'Liberté 6'), ('Louga', 'Louga'), ('Malika', 'Malika'), ('Matam', 'Matam'), ('Mbacké', 'Mbacké'), ('Mbour', 'Mbour'), ('Mermoz', 'Mermoz'), ('Médina', 'Médina'), ('Médina Coura', 'Médina Coura'), ('Médina Gounass', 'Médina Gounass'), ('Mékhé', 'Mékhé'), ('Ngor', 'Ngor'), ('Nioro du Rip', 'Nioro du Rip'), ('Nord Foire', 'Nord Foire'), ('Ouakam', 'Ouakam'), ('Ourossogui', 'Ourossogui'), ('Palais de Justice', 'Palais de Justice'), ('Parcelles Assainies', 'Parcelles Assainies'), ('Petersen', 'Petersen'), ('Pikine', 'Pikine'), ('Plateau', 'Plateau'), ('Point E', 'Point E'), ('Port Autonome de Dakar', 'Port Autonome de Dakar'), ('Richard-Toll', 'Richard-Toll'), ('Rufisque', 'Rufisque'), ('Saint-Louis', 'Saint-Louis'), ('Sandaga', 'Sandaga'), ('Sangalkam', 'Sangalkam'), ('Sicap Amitié', 'Sicap Amitié'), ('Sicap Baobab', 'Sicap Baobab'), ('Sicap Karack', 'Sicap Karack'), ('Sicap Liberté', 'Sicap Liberté'), ('Sicap Mbao', 'Sicap Mbao'), ('Sicap Mermoz', 'Sicap Mermoz'), ('Sicap Rue 10', 'Sicap Rue 10'), ('Sicap Sacré Coeur', 'Sicap Sacré Coeur'), ('Sokone', 'Sokone'), ('Sédhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thiaroye', 'Thiaroye'), ('Thies', 'Thies'), ('Tivaouane', 'Tivaouane'), ('Touba', 'Touba'), ('Vélingara', 'Vélingara'), ('Yeumbeul', 'Yeumbeul'), ('Yoff', 'Yoff'), ('Ziguinchor', 'Ziguinchor')], max_length=100)),
                ('end_city', models.CharField(choices=[('Almadies', 'Almadies'), ('Aéroport AIBD', 'Aéroport AIBD'), ('Bambilor', 'Bambilor'), ('Bargny', 'Bargny'), ('Ben Baraque', 'Ben Baraque'), ('Ben Tally', 'Ben Tally'), ('Bignona', 'Bignona'), ('Castor', 'Castor'), ('Centre Cutlure de Diamniadio', 'Centre Cutlure de Diamniadio'), ('Colobane', 'Colobane'), ('Dakar', 'Dakar'), ('Derklé', 'Derklé'), ('Diamniadio', 'Diamniadio'), ('Dieuppeul', 'Dieuppeul'), ('Diourbel', 'Diourbel'), ('Fann', 'Fann'), ('Fass', 'Fass'), ('Fatick', 'Fatick'), ('Goudomp', 'Goudomp'), ('Grand Dakar', 'Grand Dakar'), ('Grand Yoff', 'Grand Yoff'), ('Guinguinéo', 'Guinguinéo'), ('Guédiawaye', 'Guédiawaye'), ('HLM', 'HLM'), ('Hann', 'Hann'), ('Kaffrine', 'Kaffrine'), ('Kanel', 'Kanel'), ('Kaolack', 'Kaolack'), ('Keur Massar', 'Keur Massar'), ('Keur Ndiaye Lo', 'Keur Ndiaye Lo'), ('Kolda', 'Kolda'), ('Koumpentoum', 'Koumpentoum'), ('Koungheul', 'Koungheul'), ('Kounoune', 'Kounoune'), ('Kédougou', 'Kédougou'), ('Lac Rose', 'Lac Rose'), ('Liberté 5', 'Liberté 5'), ('Liberté 6', 'Liberté 6'), ('Louga', 'Louga'), ('Malika', 'Malika'), ('Matam', 'Matam'), ('Mbacké', 'Mbacké'), ('Mbour', 'Mbour'), ('Mermoz', 'Mermoz'), ('Médina', 'Médina'), ('Médina Coura', 'Médina Coura'), ('Médina Gounass', 'Médina Gounass'), ('Mékhé', 'Mékhé'), ('Ngor', 'Ngor'), ('Nioro du Rip', 'Nioro du Rip'), ('Nord Foire', 'Nord Foire'), ('Ouakam', 'Ouakam'), ('Ourossogui', 'Ourossogui'), ('Palais de Justice', 'Palais de Justice'), ('Parcelles Assainies', 'Parcelles Assainies'), ('Petersen', 'Petersen'), ('Pikine', 'Pikine'), ('Plateau', 'Plateau'), ('Point E', 'Point E'), ('Port Autonome de Dakar', 'Port Autonome de Dakar'), ('Richard-Toll', 'Richard-Toll'), ('Rufisque', 'Rufisque'), ('Saint-Louis', 'Saint-Louis'), ('Sandaga', 'Sandaga'), ('Sangalkam', 'Sangalkam'), ('Sicap Amitié', 'Sicap Amitié'), ('Sicap Baobab', 'Sicap Baobab'), ('Sicap Karack', 'Sicap Karack'), ('Sicap Liberté', 'Sicap Liberté'), ('Sicap Mbao', 'Sicap Mbao'), ('Sicap Mermoz', 'Sicap Mermoz'), ('Sicap Rue 10', 'Sicap Rue 10'), ('Sicap Sacré Coeur', 'Sicap Sacré Coeur'), ('Sokone', 'Sokone'), ('Sédhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thiaroye', 'Thiaroye'), ('Thies', 'Thies'), ('Tivaouane', 'Tivaouane'), ('Touba', 'Touba'), ('Vélingara', 'Vélingara'), ('Yeumbeul', 'Yeumbeul'), ('Yoff', 'Yoff'), ('Ziguinchor', 'Ziguinchor')], max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('seat_go', models.PositiveIntegerField()),
                ('seat_back', models.PositiveIntegerField(blank=True, null=True)),
                ('luggage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('premium', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_city', 'end_city'],
            },
        ),
    ]
