# Generated by Django 4.2.6 on 2024-05-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
        ("trips", "0003_car_trip_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="cars.car",
            ),
        ),
        migrations.DeleteModel(
            name="Car",
        ),
    ]
