# Generated by Django 4.2.6 on 2024-06-29 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_alter_trip_car_delete_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="luggage",
        ),
    ]
