# Generated by Django 4.2.6 on 2024-06-29 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_remove_trip_luggage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="seat_back",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="status",
        ),
    ]
