# Generated by Django 4.2.6 on 2024-08-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0010_alter_trip_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="seat_back",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
