# Generated by Django 4.2.6 on 2024-08-19 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0011_trip_seat_back"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="car",
        ),
    ]
