# Generated by Django 4.2.6 on 2024-08-19 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0012_remove_trip_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="trip_type",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="weekdays",
        ),
    ]
