# Generated by Django 4.2.6 on 2024-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0013_remove_trip_trip_type_remove_trip_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cabin_baggage_12kg",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="checked_baggage_23kg",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
