# Generated by Django 4.2.6 on 2024-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0016_trip_role_alter_trip_end_city_alter_trip_start_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.CharField(
                choices=[("one_way", "Aller simple"), ("round_trip", "Aller-retour")],
                default="one_way",
                max_length=10,
            ),
        ),
    ]
